# Generated by Django 4.0.1 on 2022-01-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20191017_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='linked_resources',
            field=models.ManyToManyField(blank=True, to='resource.Resource'),
        ),
    ]
